list/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "home", to: "home#index"

  root "home#index"

  get "estudantes", to: "estudantes#index", as: "estudantes"
  
end

list/app/controllers/estudantes_controller.rb
class EstudantesController < ApplicationController

  def index
    @lista_estudantes = lista_estudantes
  end

  def lista_estudantes
    [
      {
        nome: 'Amanda',
        idade: '24',
        curso: 'Administração'
      },
      {
        nome: 'Camila',
        idade: '28',
        curso: 'Engenharia'
      },
      {
        nome: 'Luiz',
        idade: '20',
        curso: 'Educação Fisica'
      }
    ]
  end

end

list/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # render "home"
    # render html: "<h1>Renderizou html</h1>".html_safe
  end

end

list/app/views/estudantes/index.html.erb
<h1>Estudantes</h1>

<div class="accordion" id="accordionExample">

  <% @lista_estudantes.each do |estudante| %>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#<%= estudante[:nome] %>" aria-expanded="true" aria-controls="<%= estudante[:nome] %>">
        <%= estudante[:nome] %>
      </button>
    </h2>
    <div id="<%= estudante[:nome] %>" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p><strong>Idade</strong> <%= estudante[:idade] %></p>
        <p><strong>Curso</strong> <%= estudante[:curso] %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

list/app/views/home/index.html.erb
<h1>Home</h1>

<%= link_to "Lista de estudantes", estudantes_path %>

list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>